version: '3.8'
services:
  tasks-db:
    image: postgres:14
    ports:
      - '5436:5432'
    env_file:
      - .env
    networks:
      - tasks-service

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - tasks-service

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'

networks:
  tasks-service:
