version: '3.8'
services:
  tasks-db:
    image: postgres:14
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_USER=johnflavian
      - POSTGRES_PASSWORD=johnny2023
      - POSTGRES_DB=tasksdb
    networks:
      - tasks-service

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - tasks-service

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'

networks:
  tasks-service:
